name: Android CI

on:
  workflow_dispatch:

jobs:
#only for debug
  DebugBuild:
    strategy:
      matrix:
        # arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
        arch: [ "arm64" ]
      fail-fast: false
    env:
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      OAUTH_API_KEY: ${{ secrets.OAUTH_API_KEY }}
    name: Build Debug ${{matrix.arch}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build debug apk
        run: |
          chmod +x gradlew
          ./gradlew assembledebug -Darch=${{matrix.arch}} --stacktrace

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-all
          path: FCL/build/outputs/*
          retention-days: 7
